GET http://localhost:3002/api/notes
###
DELETE http://localhost:3002/api/persons/2
###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Jane Robertson",
    "number": "888-555-3421"
}